### ISSUE TITLE
ACTVIDAD 10

### ISSUE THREAD

**Issue by AricelCastro** [SistemasTecTlaxiaco/actividad-10-practica-de-arquitectura-equipo-naa#1]
[DIAGRAMA DE COMPONENTES......pdf](https://github.com/user-attachments/files/18086674/DIAGRAMA.DE.COMPONENTES.pdf)

**Comment by GibranVasquez** [comment]
24
Solo hizo falta imágenes y mas texto

**Comment by josealfredo79** [comment]
hay que revisar y hacer bien el trabajo por favor..

**Comment by AricelCastro** [comment]
corregido

**Comment by josealfredo79** [comment]
Revisado...
